/*
* Copyright 2021-2022 NXP
* All rights reserved.
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_0_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_0_FUNC_ALT5 0x05u
/*!
 * @brief
 * Select function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_0_MODE_PULL_DOWN 0x03u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u
/*!
 * @brief
 * Select function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_15_MODE_PULL_DOWN 0x03u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_1_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_1_FUNC_ALT5 0x05u
/*!
 * @brief
 * Select function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_1_MODE_PULL_DOWN 0x03u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_20_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_20_FUNC_ALT0 0x00u
/*!
 * @brief
 * Select function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_20_MODE_PULL_DOWN 0x03u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_2_FUNC_ALT5 0x05u
/*!
 * @brief
 * Select function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO0_2_MODE_PULL_DOWN 0x03u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_3_FUNC_ALT5 0x05u
/*!
 * @brief Select function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_3_MODE_PULL_UP 0x00u

/*! @name PIO0_20 (number 24), HELIOS_GPIO3_SYNC
  @{ */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_PIN  20U  /*!<@brief 0U pin index: 20 */
                                                        /* @} */

/*! @name PIO0_15 (number 18), HELIOS_GPIO5_HOST_INT
  @{ */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_PIN  15U  /*!<@brief 0U pin index: 15 */
                                                            /* @} */

/*! @name PIO0_17 (number 21), HeliosCE
  @{ */
#define RV4_INIT_HELIOSPINS_HELIOS_CE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_HELIOSPINS_HELIOS_CE_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_HELIOSPINS_HELIOS_CE_PIN  17U  /*!<@brief 0U pin index: 17 */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_HeliosPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_15_FUNC_ALT0 0x00u

/*! @name PIO0_15 (number 18), HELIOS_GPIO5_HOST_INT
  @{ */
#define RV4_INIT_HELIOSIRQPINS_HELIOS_GPIO5_HOST_INT_PORT 0U  /*!<@brief PORT device name: 0U */
#define RV4_INIT_HELIOSIRQPINS_HELIOS_GPIO5_HOST_INT_PIN  15U /*!<@brief 0U pin index: 15 */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_HeliosIRQPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_8_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_8_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_9_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_9_FUNC_ALT2 0x02u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_UARTPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_10_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_11_FUNC_ALT5 0x05u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_I2CPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_12_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_12_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_13_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 5. */
#define PIO0_14_FUNC_ALT5 0x05u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_SWDPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 7. */
#define PIO0_16_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 7. */
#define PIO0_18_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 7. */
#define PIO0_19_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_21_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 7. */
#define PIO0_21_FUNC_ALT7 0x07u

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_SPIFIPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_ISPPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u

/*! @name PIO0_17 (number 21), HeliosCE
  @{ */
#define RV4_INIT_HELIOSCEPIN_HELIOS_CE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_HELIOSCEPIN_HELIOS_CE_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_HELIOSCEPIN_HELIOS_CE_PIN  17U  /*!<@brief 0U pin index: 17 */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_HeliosCEPin(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_6_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 2. */
#define PIO0_7_FUNC_ALT2 0x02u

/*! @name USART0_CTS (number 10), VENUS_VEN
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
#if HW_FLOW_CONTROL_SUPPORT
void RV4_Init_HW_FlowPins(void); /* Function assigned for the Cortex-M4 */
#endif
/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_7_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_7_FUNC_ALT0 0x00u

/*! @name PIO0_7 (number 10), VENUS_VEN
  @{ */
#define RV4_INIT_VENUSPINS_VENUS_VEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_VENUSPINS_VENUS_VEN_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_VENUSPINS_VENUS_VEN_PIN  7U   /*!<@brief 0U pin index: 7 */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_VenusPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_17_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_17_FUNC_ALT0 0x00u

/*! @name PIO0_17 (number 21), HeliosCE
  @{ */
#define RV4_INIT_REVC_VENUSIRQPINS_VENUS_IRQ_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_REVC_VENUSIRQPINS_VENUS_IRQ_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_REVC_VENUSIRQPINS_VENUS_IRQ_PIN  17U  /*!<@brief 0U pin index: 17 */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_RevC_VenusIRQPins(void); /* Function assigned for the Cortex-M4 */

/*!
 * @brief Select Analog/Digital Mode.: Digital mode. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Select digital function assigned to this pin.: Alternative connection 0. */
#define PIO0_6_FUNC_ALT0 0x00u

/*! @name PIO0_6 (number 9), VENUS_IRQ
  @{ */
#define RV4_INIT_REVB_VENUSIRQPINS_VENUS_IRQ_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define RV4_INIT_REVB_VENUSIRQPINS_VENUS_IRQ_PORT 0U   /*!<@brief PORT device name: 0U */
#define RV4_INIT_REVB_VENUSIRQPINS_VENUS_IRQ_PIN  6U   /*!<@brief 0U pin index: 6 */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RV4_Init_RevB_VenusIRQPins(void); /* Function assigned for the Cortex-M4 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
