/*
* Copyright 2021-2023 NXP
* All rights reserved.
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: QN9090
package_id: QN9090THN
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: '17', pin_signal: PIO0_14/SPI1_SSELN1/USART0_SCK/CT32B0_CAP1/PWM1/SWO/MCLK/RFTX/ADC0_0, label: SWO}
- {pin_num: '18', pin_signal: PIO0_15/SPI1_SCK/ANA_COMP_OUT/PWM3/I2C0_SCL/PDM1_DATA/RFRX/ADC0_1, label: HELIOS_GPIO5_HOST_INT, identifier: HELIOS_GPIO5_HOST_INT}
- {pin_num: '7', pin_signal: PIO0_4/SPI0_MOSI/USART0_CTS/PWM4/SPI1_SSELN1/ISO7816_IO/RFTX, label: ISP_SEL}
- {pin_num: '24', pin_signal: PIO0_20/IR_BLASTER/USART1_TXD/PWM8/RFTX/SPIFI_IO2/ACP, label: HELIOS_GPIO3_SYNC, identifier: HELIOS_GPIO3_SYNC}
- {pin_num: '8', pin_signal: PIO0_5/SPI0_SSELN/USART0_RTS/SPI1_MISO/SPI1_SSELN2/RFRX, label: ISP_ENTRY}
- {pin_num: '3', pin_signal: PIO0_0/USART0_SCK/USART1_TXD/PWM0/SPI1_SCK/PDM0_DATA, label: SCK}
- {pin_num: '4', pin_signal: PIO0_1/USART1_RXD/PWM1/SPI1_MISO/PDM0_CLK, label: SDO}
- {pin_num: '5', pin_signal: PIO0_2/SPI0_SCK/USART0_RXD/PWM2/SPI1_MOSI/ISO7816_RST/MCLK, label: SDI}
- {pin_num: '6', pin_signal: PIO0_3/SPI0_MISO/USART0_TXD/PWM3/SPI1_SSELN0/ISO7816_CLK, label: CS_N}
- {pin_num: '21', pin_signal: PIO0_17/SPI1_MOSI/ISO7816_CLK/SWO/PWM6/CLK_OUT/SPIFI_IO3/ADC0_3, label: HeliosCE, identifier: HELIOS_CE;VENUS_IRQ}
- {pin_num: '9', pin_signal: PIO0_6/SPI0_SCK/USART0_RTS/CT32B1_MAT0/PWM6/I2C1_SCL/USART1_TXD/ADE, label: VENUS_IRQ, identifier: VENUS_IRQ}
- {pin_num: '10', pin_signal: PIO0_7/SPI0_MISO/USART0_CTS/CT32B1_MAT1/PWM7/I2C1_SDA/USART1_RXD/ADO, label: VENUS_VEN, identifier: VENUS_VEN}
- {pin_num: '16', pin_signal: PIO0_13/SPI1_SSELN2/SWDIO/PWM2/I2C1_SDA/SPI0_SSELN, label: SWDIO}
- {pin_num: '15', pin_signal: PIO0_12/IR_BLASTER/SWCLK/PWM0/I2C1_SCL/SPI0_MOSI/ANA_COMP_OUT, label: SWCLK}
- {pin_num: '13', pin_signal: PIO0_10/CT32B0_CAP0/USART1_TXD/RFTX/I2C0_SCL/SPI0_SCK/PDM0_DATA, label: I2C0_SCL_SN}
- {pin_num: '14', pin_signal: PIO0_11/CT32B1_CAP0/USART1_RXD/RFRX/I2C0_SDA/SPI0_MISO/PDM0_CLK, label: I2C_SDA_SN}
- {pin_num: '11', pin_signal: PIO0_8/SPI0_MOSI/USART0_TXD/CT32B0_MAT0/PWM8/ANA_COMP_OUT/RFTX/PDM1_DATA, label: UART0_TXD}
- {pin_num: '12', pin_signal: PIO0_9/SPI0_SSELN/USART0_RXD/CT32B1_CAP1/PWM9/USART1_SCK/ADO/PDM1_CLK, label: UART0_RXD}
- {pin_num: '19', pin_signal: PIO0_16/SPI1_SSELN0/ISO7816_RST/PWM5/I2C0_SDA/PDM1_CLK/SPIFI_CSN/ADC0_2, label: SPIFI_CSN}
- {pin_num: '22', pin_signal: PIO0_18/SPI1_MISO/ISO7816_IO/CT32B0_MAT1/PWM7/USART0_TXD/SPIFI_CLK/ADC0_4, label: SPIFI_CLK}
- {pin_num: '23', pin_signal: PIO0_19/ADO/USART1_RXD/CLK_IN/PWM4/USART0_RXD/SPIFI_IO0/ADC0_5, label: SPIFI_MOSI}
- {pin_num: '25', pin_signal: PIO0_21/IR_BLASTER/USART1_SCK/PWM9/RFRX/SWO/SPIFI_IO1/ACM, label: SPIFI_MISO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    RV4_Init_HeliosPins();
    RV4_Init_UARTPins();
    RV4_Init_I2CPins();
    RV4_Init_SWDPins();
    RV4_Init_SPIFIPins();
#if HW_FLOW_CONTROL_SUPPORT
    RV4_Init_HW_FlowPins();
#endif
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_HeliosPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '4', peripheral: SPI1, signal: MISO, pin_signal: PIO0_1/USART1_RXD/PWM1/SPI1_MISO/PDM0_CLK, mode: pullDown}
  - {pin_num: '5', peripheral: SPI1, signal: MOSI, pin_signal: PIO0_2/SPI0_SCK/USART0_RXD/PWM2/SPI1_MOSI/ISO7816_RST/MCLK, mode: pullDown}
  - {pin_num: '3', peripheral: SPI1, signal: SCK, pin_signal: PIO0_0/USART0_SCK/USART1_TXD/PWM0/SPI1_SCK/PDM0_DATA, mode: pullDown}
  - {pin_num: '6', peripheral: SPI1, signal: SSELN0, pin_signal: PIO0_3/SPI0_MISO/USART0_TXD/PWM3/SPI1_SSELN0/ISO7816_CLK, mode: pullUp}
  - {pin_num: '24', peripheral: GPIO, signal: 'PIO0, 20', pin_signal: PIO0_20/IR_BLASTER/USART1_TXD/PWM8/RFTX/SPIFI_IO2/ACP, direction: OUTPUT, gpio_init_state: 'false',
    mode: pullDown}
  - {pin_num: '18', peripheral: GPIO, signal: 'PIO0, 15', pin_signal: PIO0_15/SPI1_SCK/ANA_COMP_OUT/PWM3/I2C0_SCL/PDM1_DATA/RFRX/ADC0_1, direction: INPUT, mode: pullDown}
  - {pin_num: '21', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/SPI1_MOSI/ISO7816_CLK/SWO/PWM6/CLK_OUT/SPIFI_IO3/ADC0_3, identifier: HELIOS_CE, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_HeliosPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_HeliosPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t HELIOS_GPIO5_HOST_INT_config = {.pinDirection = kGPIO_DigitalInput, .outputLogic = 0U};
    /* Initialize GPIO functionality on pin PIO0_15 (pin 18)  */
    GPIO_PinInit(RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_GPIO,
        RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_PORT,
        RV4_INIT_HELIOSPINS_HELIOS_GPIO5_HOST_INT_PIN,
        &HELIOS_GPIO5_HOST_INT_config);

#if 0
    /* for RV4 RevC this pin is used as interrupt for SN */
    gpio_pin_config_t HELIOS_CE_config = {.pinDirection = kGPIO_DigitalOutput, .outputLogic = 0U};
    /* Initialize GPIO functionality on pin PIO0_17 (pin 21)  */
    GPIO_PinInit(RV4_INIT_HELIOSPINS_HELIOS_CE_GPIO,
        RV4_INIT_HELIOSPINS_HELIOS_CE_PORT,
        RV4_INIT_HELIOSPINS_HELIOS_CE_PIN,
        &HELIOS_CE_config);
#endif
    gpio_pin_config_t HELIOS_GPIO3_SYNC_config = {.pinDirection = kGPIO_DigitalOutput, .outputLogic = 0U};
    /* Initialize GPIO functionality on pin PIO0_20 (pin 24)  */
    GPIO_PinInit(RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_GPIO,
        RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_PORT,
        RV4_INIT_HELIOSPINS_HELIOS_GPIO3_SYNC_PIN,
        &HELIOS_GPIO3_SYNC_config);

    IOCON->PIO[0][0] = ((IOCON->PIO[0][0] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT00 (pin 3) is configured as SPI1_SCK. */
                        | IOCON_PIO_FUNC(PIO0_0_FUNC_ALT5)

                        /* Select function mode (on-chip pull-up/pull-down resistor control).
                         * : Pull-down.
                         * Pull-down resistor enabled. */
                        | IOCON_PIO_MODE(PIO0_0_MODE_PULL_DOWN)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_0_DIGIMODE_DIGITAL));

    IOCON->PIO[0][1] = ((IOCON->PIO[0][1] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT01 (pin 4) is configured as SPI1_MISO. */
                        | IOCON_PIO_FUNC(PIO0_1_FUNC_ALT5)

                        /* Select function mode (on-chip pull-up/pull-down resistor control).
                         * : Pull-down.
                         * Pull-down resistor enabled. */
                        | IOCON_PIO_MODE(PIO0_1_MODE_PULL_DOWN)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_1_DIGIMODE_DIGITAL));

    IOCON->PIO[0][15] = ((IOCON->PIO[0][15] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                 IOCON_PIO_OD_MASK))) // added OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT015 (pin 18) is configured as PIO0_15. */
                         | IOCON_PIO_FUNC(PIO0_15_FUNC_ALT0)

                         /* Select function mode (on-chip pull-up/pull-down resistor control).
                          * : Pull-down.
                          * Pull-down resistor enabled. */
                         | IOCON_PIO_MODE(PIO0_15_MODE_PULL_DOWN)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_15_DIGIMODE_DIGITAL));

#if 0
    /* for RV4 RevC this pin is used as interrupt for SN */
    IOCON->PIO[0][17] = ((IOCON->PIO[0][17] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT017 (pin 21) is configured as PIO0_17. */
                         | IOCON_PIO_FUNC(PIO0_17_FUNC_ALT0)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_17_DIGIMODE_DIGITAL));
#endif

    IOCON->PIO[0][2] = ((IOCON->PIO[0][2] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT02 (pin 5) is configured as SPI1_MOSI. */
                        | IOCON_PIO_FUNC(PIO0_2_FUNC_ALT5)

                        /* Select function mode (on-chip pull-up/pull-down resistor control).
                         * : Pull-down.
                         * Pull-down resistor enabled. */
                        | IOCON_PIO_MODE(PIO0_2_MODE_PULL_DOWN)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_2_DIGIMODE_DIGITAL));

    IOCON->PIO[0][20] = ((IOCON->PIO[0][20] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT020 (pin 24) is configured as PIO0_20. */
                         | IOCON_PIO_FUNC(PIO0_20_FUNC_ALT0)

                         /* Select function mode (on-chip pull-up/pull-down resistor control).
                          * : Pull-down.
                          * Pull-down resistor enabled. */
                         | IOCON_PIO_MODE(PIO0_20_MODE_PULL_DOWN)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_20_DIGIMODE_DIGITAL));

    IOCON->PIO[0][3] = ((IOCON->PIO[0][3] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                IOCON_PIO_OD_MASK))) // added OD mask

                        /* Select digital function assigned to this pin.
                         * : PORT03 (pin 6) is configured as SPI1_SSELN0. */
                        | IOCON_PIO_FUNC(PIO0_3_FUNC_ALT5)

                        /* Select function mode (on-chip pull-up/pull-down resistor control).
                         * : Pull-up.
                         * Pull-up resistor enabled. */
                        | IOCON_PIO_MODE(PIO0_3_MODE_PULL_UP)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_3_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_HeliosIRQPins:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: PINT, signal: 'PINT, 0', pin_signal: PIO0_15/SPI1_SCK/ANA_COMP_OUT/PWM3/I2C0_SCL/PDM1_DATA/RFRX/ADC0_1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_HeliosIRQPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_HeliosIRQPins(void)
{
    /* Enables the clock for the Input Mux. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* PIO0_15 is selected for PINT input 0 */
    INPUTMUX_AttachSignal(INPUTMUX, 0U, kINPUTMUX_GpioPort0Pin15ToPintsel);

    IOCON->PIO[0][15] = ((IOCON->PIO[0][15] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK | IOCON_PIO_OD_MASK))) // added OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT015 (pin 18) is configured as PIO0_15. */
                         | IOCON_PIO_FUNC(PIO0_15_FUNC_ALT0)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_15_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_UARTPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: USART0, signal: TXD, pin_signal: PIO0_8/SPI0_MOSI/USART0_TXD/CT32B0_MAT0/PWM8/ANA_COMP_OUT/RFTX/PDM1_DATA}
  - {pin_num: '12', peripheral: USART0, signal: RXD, pin_signal: PIO0_9/SPI0_SSELN/USART0_RXD/CT32B1_CAP1/PWM9/USART1_SCK/ADO/PDM1_CLK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_UARTPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][8] = ((IOCON->PIO[0][8] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT08 (pin 11) is configured as USART0_TXD. */
                        | IOCON_PIO_FUNC(PIO0_8_FUNC_ALT2)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_8_DIGIMODE_DIGITAL));

    IOCON->PIO[0][9] = ((IOCON->PIO[0][9] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK))) // added MODE mask

                        /* Select digital function assigned to this pin.
                         * : PORT09 (pin 12) is configured as USART0_RXD. */
                        | IOCON_PIO_FUNC(PIO0_9_FUNC_ALT2)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_9_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_I2CPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '13', peripheral: I2C0, signal: SCL, pin_signal: PIO0_10/CT32B0_CAP0/USART1_TXD/RFTX/I2C0_SCL/SPI0_SCK/PDM0_DATA}
  - {pin_num: '14', peripheral: I2C0, signal: SDA, pin_signal: PIO0_11/CT32B1_CAP0/USART1_RXD/RFRX/I2C0_SDA/SPI0_MISO/PDM0_CLK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_I2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_I2CPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][10] = ((IOCON->PIO[0][10] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                 IOCON_PIO_OD_MASK))) // added MODE, OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT010 (pin 13) is configured as I2C0_SCL. */
                         | IOCON_PIO_FUNC(PIO0_10_FUNC_ALT5) |
                         IOCON_PIO_EGP(0) // added EGP.
                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_10_DIGIMODE_DIGITAL));

    IOCON->PIO[0][11] = ((IOCON->PIO[0][11] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                 IOCON_PIO_OD_MASK))) // added MODE, OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT011 (pin 14) is configured as I2C0_SDA. */
                         | IOCON_PIO_FUNC(PIO0_11_FUNC_ALT5) |
                         IOCON_PIO_EGP(0) // added EGP.
                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_11_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_SWDPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '15', peripheral: SWD, signal: SWCLK, pin_signal: PIO0_12/IR_BLASTER/SWCLK/PWM0/I2C1_SCL/SPI0_MOSI/ANA_COMP_OUT}
  - {pin_num: '16', peripheral: SWD, signal: SWDIO, pin_signal: PIO0_13/SPI1_SSELN2/SWDIO/PWM2/I2C1_SDA/SPI0_SSELN}
  - {pin_num: '17', peripheral: SWD, signal: SWO, pin_signal: PIO0_14/SPI1_SSELN1/USART0_SCK/CT32B0_CAP1/PWM1/SWO/MCLK/RFTX/ADC0_0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_SWDPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_SWDPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][12] = ((IOCON->PIO[0][12] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT012 (pin 15) is configured as SWCLK. */
                         | IOCON_PIO_FUNC(PIO0_12_FUNC_ALT2)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_12_DIGIMODE_DIGITAL));

    IOCON->PIO[0][13] = ((IOCON->PIO[0][13] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT013 (pin 16) is configured as SWDIO. */
                         | IOCON_PIO_FUNC(PIO0_13_FUNC_ALT2)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_13_DIGIMODE_DIGITAL));

    IOCON->PIO[0][14] = ((IOCON->PIO[0][14] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                 IOCON_PIO_OD_MASK))) // added MODE, OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT014 (pin 17) is configured as SWO. */
                         | IOCON_PIO_FUNC(PIO0_14_FUNC_ALT5) |
                         IOCON_PIO_MODE(0) // set mode to pull-up
                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_14_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_SPIFIPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '22', peripheral: SPIFI, signal: CLK, pin_signal: PIO0_18/SPI1_MISO/ISO7816_IO/CT32B0_MAT1/PWM7/USART0_TXD/SPIFI_CLK/ADC0_4}
  - {pin_num: '19', peripheral: SPIFI, signal: CSN, pin_signal: PIO0_16/SPI1_SSELN0/ISO7816_RST/PWM5/I2C0_SDA/PDM1_CLK/SPIFI_CSN/ADC0_2}
  - {pin_num: '23', peripheral: SPIFI, signal: SPIFI_IO0_or_SPIFI_MOSI, pin_signal: PIO0_19/ADO/USART1_RXD/CLK_IN/PWM4/USART0_RXD/SPIFI_IO0/ADC0_5}
  - {pin_num: '25', peripheral: SPIFI, signal: SPIFI_IO1_or_SPIFI_MISO, pin_signal: PIO0_21/IR_BLASTER/USART1_SCK/PWM9/RFRX/SWO/SPIFI_IO1/ACM}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_SPIFIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_SPIFIPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][16] = ((IOCON->PIO[0][16] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                 IOCON_PIO_OD_MASK))) // added MODE, OD mask

                         /* Select digital function assigned to this pin.
                          * : PORT016 (pin 19) is configured as SPIFI_CSN. */
                         | IOCON_PIO_FUNC(PIO0_16_FUNC_ALT7) |
                         IOCON_PIO_MODE(0) // set mode to pull-up
                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_16_DIGIMODE_DIGITAL));

    IOCON->PIO[0][18] = ((IOCON->PIO[0][18] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT018 (pin 22) is configured as SPIFI_CLK. */
                         | IOCON_PIO_FUNC(PIO0_18_FUNC_ALT7)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_18_DIGIMODE_DIGITAL));

    IOCON->PIO[0][19] =
        ((IOCON->PIO[0][19] &
             /* Mask bits to zero which are setting */
             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK))) // added MODE mask

            /* Select digital function assigned to this pin.
                          * : PORT019 (pin 23) is configured as SPIFI_IO0. */
            | IOCON_PIO_FUNC(PIO0_19_FUNC_ALT7) |
            IOCON_PIO_MODE(3) // set mode to pull-down
            /* Select Analog/Digital Mode.
                          * : Digital mode. */
            | IOCON_PIO_DIGIMODE(PIO0_19_DIGIMODE_DIGITAL));

    IOCON->PIO[0][21] = ((IOCON->PIO[0][21] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT021 (pin 25) is configured as SPIFI_IO1. */
                         | IOCON_PIO_FUNC(PIO0_21_FUNC_ALT7)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_21_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_ISPPins:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_ISPPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_ISPPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_HeliosCEPin:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '21', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/SPI1_MOSI/ISO7816_CLK/SWO/PWM6/CLK_OUT/SPIFI_IO3/ADC0_3, identifier: HELIOS_CE, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_HeliosCEPin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_HeliosCEPin(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t HELIOS_CE_config = {.pinDirection = kGPIO_DigitalOutput, .outputLogic = 0U};
    /* Initialize GPIO functionality on pin PIO0_17 (pin 21)  */
    GPIO_PinInit(RV4_INIT_HELIOSCEPIN_HELIOS_CE_GPIO,
        RV4_INIT_HELIOSCEPIN_HELIOS_CE_PORT,
        RV4_INIT_HELIOSCEPIN_HELIOS_CE_PIN,
        &HELIOS_CE_config);

    IOCON->PIO[0][17] = ((IOCON->PIO[0][17] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT017 (pin 21) is configured as PIO0_17. */
                         | IOCON_PIO_FUNC(PIO0_17_FUNC_ALT0)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_17_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_HW_FlowPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '9', peripheral: USART0, signal: RTS, pin_signal: PIO0_6/SPI0_SCK/USART0_RTS/CT32B1_MAT0/PWM6/I2C1_SCL/USART1_TXD/ADE, identifier: ''}
  - {pin_num: '10', peripheral: USART0, signal: CTS, pin_signal: PIO0_7/SPI0_MISO/USART0_CTS/CT32B1_MAT1/PWM7/I2C1_SDA/USART1_RXD/ADO}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_HW_FlowPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
#if HW_FLOW_CONTROL_SUPPORT
void RV4_Init_HW_FlowPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);

    IOCON->PIO[0][6] = ((IOCON->PIO[0][6] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT06 (pin 9) is configured as USART0_RTS. */
                        | IOCON_PIO_FUNC(PIO0_6_FUNC_ALT2)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_6_DIGIMODE_DIGITAL));

    IOCON->PIO[0][7] = ((IOCON->PIO[0][7] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT07 (pin 10) is configured as USART0_CTS. */
                        | IOCON_PIO_FUNC(PIO0_7_FUNC_ALT2)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_7_DIGIMODE_DIGITAL));
}
#endif

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_VenusPins:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7/SPI0_MISO/USART0_CTS/CT32B1_MAT1/PWM7/I2C1_SDA/USART1_RXD/ADO, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_VenusPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_VenusPins(void)
{
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t VENUS_VEN_config = {.pinDirection = kGPIO_DigitalOutput, .outputLogic = 0U};
    /* Initialize GPIO functionality on pin PIO0_7 (pin 10)  */
    GPIO_PinInit(RV4_INIT_VENUSPINS_VENUS_VEN_GPIO,
        RV4_INIT_VENUSPINS_VENUS_VEN_PORT,
        RV4_INIT_VENUSPINS_VENUS_VEN_PIN,
        &VENUS_VEN_config);

    IOCON->PIO[0][7] = ((IOCON->PIO[0][7] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                        /* Select digital function assigned to this pin.
                         * : PORT07 (pin 10) is configured as PIO0_7. */
                        | IOCON_PIO_FUNC(PIO0_7_FUNC_ALT0)

                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_7_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_RevC_VenusIRQPins:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '21', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/SPI1_MOSI/ISO7816_CLK/SWO/PWM6/CLK_OUT/SPIFI_IO3/ADC0_3, identifier: VENUS_IRQ, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_RevC_VenusIRQPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_RevC_VenusIRQPins(void)
{
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    INPUTMUX_AttachSignal(INPUTMUX, 1U, kINPUTMUX_GpioPort0Pin17ToPintsel);
    /* Initialize GPIO functionality on pin PIO0_17 (pin 21)  */

    IOCON->PIO[0][17] = ((IOCON->PIO[0][17] &
                             /* Mask bits to zero which are setting */
                             (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Select digital function assigned to this pin.
                          * : PORT017 (pin 21) is configured as PIO0_17. */
                         | IOCON_PIO_FUNC(PIO0_17_FUNC_ALT0)

                         /* Select Analog/Digital Mode.
                          * : Digital mode. */
                         | IOCON_PIO_DIGIMODE(PIO0_17_DIGIMODE_DIGITAL));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
RV4_Init_RevB_VenusIRQPins:
- options: {callFromInitBoot: 'false', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: '9', peripheral: PINT, signal: 'PINT, 1', pin_signal: PIO0_6/SPI0_SCK/USART0_RTS/CT32B1_MAT0/PWM6/I2C1_SCL/USART1_TXD/ADE}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : RV4_Init_RevB_VenusIRQPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M4 */
void RV4_Init_RevB_VenusIRQPins(void)
{
    /* Enables the clock for the Input Mux. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* Enables the clock for the I/O controller block. 0: Disable. 1: Enable.: 0x01u */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* PIO0_6 is selected for PINT input 1 */
    INPUTMUX_AttachSignal(INPUTMUX, 1U, kINPUTMUX_GpioPort0Pin6ToPintsel);

    IOCON->PIO[0][6] = ((IOCON->PIO[0][6] &
                            /* Mask bits to zero which are setting */
                            (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK |
                                IOCON_PIO_OD_MASK))) // added MODE, OD mask

                        /* Select digital function assigned to this pin.
                         * : PORT06 (pin 9) is configured as PIO0_6. */
                        | IOCON_PIO_FUNC(PIO0_6_FUNC_ALT0) |
                        IOCON_PIO_MODE(3) // set mode to pull-down
                        /* Select Analog/Digital Mode.
                         * : Digital mode. */
                        | IOCON_PIO_DIGIMODE(PIO0_6_DIGIMODE_DIGITAL));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/