################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
boards/Host/Rhodes4 \
boards/Rhodes4_SPI \
demos/SR150_SE051W/demo_binding \
demos/SR150_SE051W/demo_fl_initiator \
demos/SR150_SE051W/demo_fl_responder \
demos/SR150_SE051W/demo_fl_responder_iot_concurrency \
demos/SR150_SE051W \
demos/SR1XX/demo_csa_controlee \
demos/SR1XX/demo_dltdoa_initiator \
demos/SR1XX/demo_dltdoa_responder \
demos/SR1XX/demo_dltdoa_tag \
demos/SR1XX/demo_hybrid_ranging_controlee \
demos/SR1XX/demo_hybrid_ranging_controller \
demos/SR1XX/demo_inband_data_transfer_rx \
demos/SR1XX/demo_inband_data_transfer_tx \
demos/SR1XX/demo_nearby_interaction \
demos/SR1XX/demo_nearby_interaction/src \
demos/SR1XX/demo_nearby_interaction_client \
demos/SR1XX/demo_nearby_interaction_client/src \
demos/SR1XX/demo_otp_storage_factory \
demos/SR1XX/demo_otp_storage_mainline \
demos/SR1XX/demo_owr_aoa_advertiser \
demos/SR1XX/demo_ranging_controlee \
demos/SR1XX/demo_ranging_controller \
demos/SR1XX/demo_test_rx \
demos/SR1XX/demo_test_tx \
demos/SR1XX/demo_ultdoa_anchor \
demos/SR1XX/demo_ultdoa_sync_anchor \
demos/SR1XX/demo_ultdoa_tag \
demos/common \
demos/mctt_pctt \
demos/mctt_pctt/handlers \
demos/pnp/Rhodes4 \
demos/pnp \
demos/se_vcom \
demos/vcom_common \
ext/boards/qn9090/bluetooth/bluetooth/common \
ext/boards/qn9090/bluetooth/bluetooth/common/gatt_db \
ext/boards/qn9090/bluetooth/bluetooth/controller/config \
ext/boards/qn9090/bluetooth/bluetooth/host/config \
ext/boards/qn9090/bluetooth/bluetooth/profiles/battery \
ext/boards/qn9090/bluetooth/bluetooth/profiles/device_info \
ext/boards/qn9090/bluetooth/bluetooth/profiles/private_profile \
ext/boards/qn9090/bluetooth/framework/Flash/External/source \
ext/boards/qn9090/bluetooth/framework/Flash \
ext/boards/qn9090/bluetooth/framework/FunctionLib/source \
ext/boards/qn9090/bluetooth/framework/GPIO/source \
ext/boards/qn9090/bluetooth/framework/Keyboard/source \
ext/boards/qn9090/bluetooth/framework/LED/source \
ext/boards/qn9090/bluetooth/framework/Lists/source \
ext/boards/qn9090/bluetooth/framework/Logging/source \
ext/boards/qn9090/bluetooth/framework/LowPower/source \
ext/boards/qn9090/bluetooth/framework/MemManager/source \
ext/boards/qn9090/bluetooth/framework/Messaging/source \
ext/boards/qn9090/bluetooth/framework/ModuleInfo/source \
ext/boards/qn9090/bluetooth/framework/NVM/source \
ext/boards/qn9090/bluetooth/framework/OSAbstraction/source \
ext/boards/qn9090/bluetooth/framework/PDM/source \
ext/boards/qn9090/bluetooth/framework/Panic/source \
ext/boards/qn9090/bluetooth/framework/RNG/source \
ext/boards/qn9090/bluetooth/framework/Reset/source \
ext/boards/qn9090/bluetooth/framework/SecLib/source \
ext/boards/qn9090/bluetooth/framework/SerialManager/source/SPI_Adapter \
ext/boards/qn9090/bluetooth/framework/TimersManager/source \
ext/boards/qn9090/bluetooth/framework/XCVR/DK6 \
ext/boards/qn9090/components/serial_manager \
ext/boards/qn9090/components/uart \
ext/boards/qn9090/devices/QN9090/drivers \
ext/boards/qn9090/devices/QN9090/gcc \
ext/boards/qn9090/devices/QN9090 \
ext/boards/qn9090/devices/QN9090/utilities \
ext/freertos \
ext/freertos/portable/GCC/ARM_CM4FQN9090 \
ext/freertos/portable/MemMang \
ext/mbedtls/library \
ext/mbedtls/port/ksdk \
libs/halimpl/fwd/SR1XX \
libs/halimpl/fwdl_provider \
libs/halimpl/hal \
libs/halimpl/log \
libs/halimpl/osal \
libs/halimpl/tml \
libs/halimpl/transport/SPI/SR1XX \
libs/halimpl/utils \
libs/uci-core/src \
libs/uwb-iot/uwb_api/Api/SE051_Wrapper \
libs/uwb-iot/uwb_api/Api/SR1XX \
libs/uwb-iot/uwb_api/Api/SR1XX/SR150 \
libs/uwb-iot/uwb_api/Api/StateMachine \
libs/uwb-iot/uwb_api/Api \
libs/uwb-iot/uwb_api/PrintUtility \
libs/uwb-iot/uwb_api/PrintUtility/SR1XX \
libs/uwb-iot/uwb_core/adaptation \
se_mw/nxp_iot_agent/src/common \
se_mw/nxp_iot_agent/src/protobuf \
se_mw/se_hostlib/hostLib/fira/src \
se_mw/se_hostlib/hostLib/libCommon/infra \
se_mw/se_hostlib/hostLib/libCommon/scp \
se_mw/se_hostlib/hostLib/libCommon/smCom/T1oI2C \
se_mw/se_hostlib/hostLib/libCommon/smCom \
se_mw/se_hostlib/hostLib/platform/ksdk \
se_mw/se_hostlib/hostLib/se05x/src \
se_mw/se_hostlib/hostLib/se05x_03_xx_xx \
se_mw/semslite/lib/src \
se_mw/sss/ex/src \
se_mw/sss/src \
se_mw/sss/src/mbedtls \
se_mw/sss/src/se05x \

